spring.application.name=api-gateway
server.port=8090
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
management.endpoints.web.exposure.include=*
# Customer Service Route
spring.cloud.gateway.server.webflux.routes[0].id=customer-service
spring.cloud.gateway.server.webflux.routes[0].uri= lb://CUSTOMER-MANAGEMENT-SERVICE
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/v1/customers/**
# Account Service Route
spring.cloud.gateway.server.webflux.routes[1].id=account-service
spring.cloud.gateway.server.webflux.routes[1].uri= lb://ACCOUNT-MANAGEMENT-SERVICE
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/v1/accounts/**

logging.level.org.springframework.cloud.gateway=TRACE
logging.level.org.springframework.web=DEBUG
spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true
